/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "stm32f446xx.h"  // CMSIS device header
#include <stdint.h>
#include "clock.h"



/* Control line */
#define LINE_RELEASE() (GPIOB->BSRR = (1U << 6))        // High-Z → pulled HIGH
#define LINE_LOW()     (GPIOB->BSRR = (1U << (6 + 16))) // Force LOW

void GPIO_PB6_OpenDrain_Init(void)
{
    /* 1. Enable GPIOB clock */
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

    /* 2. Output mode (MODER6 = 01) */
    GPIOB->MODER &= ~(3U << (6 * 2));
    GPIOB->MODER |=  (1U << (6 * 2));

    /* 3. Open-drain (OTYPER6 = 1) */
    GPIOB->OTYPER |= (1U << 6);

    /* 4. Enable pull-up (PUPDR6 = 01) */
    GPIOB->PUPDR &= ~(3U << (6 * 2));
    GPIOB->PUPDR |=  (1U << (6 * 2));
}


void delay_us(uint32_t us)
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;  // Habilitar TIM2

    // APB1 = 45 MHz → timer clock = 2×45 MHz = 90 MHz (porque APB1 prescaler != 1)
    // Queremos 1 tick = 1 µs → PSC = 90 - 1
    TIM2->PSC = 90 - 1;
    TIM2->ARR = us;
    TIM2->EGR = TIM_EGR_UG;
    TIM2->SR = 0;
    TIM2->CR1 = TIM_CR1_OPM | TIM_CR1_CEN;

    while (!(TIM2->SR & TIM_SR_UIF)); // Esperar fin
    TIM2->CR1 = 0;
    RCC->APB1ENR &= ~RCC_APB1ENR_TIM2EN;
}


int main(void) {
	SystemClock_Config_180MHz();
	GPIO_PB6_OpenDrain_Init();

    while (1) {
    	LINE_RELEASE();
    	delay_us(2000000);
    	LINE_LOW();
    	delay_us(2000000);



    }
}
